# Generated by Django 5.1.7 on 2025-04-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
