# Generated by Django 5.1.7 on 2025-04-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='image_url',
            new_name='photos',
        ),
    ]
