# Generated by Django 5.1.7 on 2025-04-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_image_url_menuitem_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='photos',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
