# Generated by Django 5.1.7 on 2025-04-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
