# Generated by Django 5.1.7 on 2025-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
