# Generated by Django 5.1.7 on 2025-04-19 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
