# Generated by Django 5.1.7 on 2025-04-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafeid', models.SlugField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='photos/')),
                ('qr', models.ImageField(upload_to='qr')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.cafemodel'),
        ),
    ]
