# Generated by Django 5.1.7 on 2025-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_cafemodel_menuitem_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemodel',
            name='qr',
            field=models.ImageField(blank=True, upload_to='qr'),
        ),
    ]
