# Generated by Django 5.1.7 on 2025-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_cafemodel_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemodel',
            name='cafeid',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
