# Generated by Django 5.1.7 on 2025-04-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Payment')], default='cash', max_length=20),
        ),
    ]
